# Generated by Django 5.2.8 on 2026-01-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Usuario',
            field=models.CharField(choices=[('CORRETOR', 'Corretor'), ('ADMIN', 'Admin')], default='CORRETOR', max_length=10),
        ),
    ]
